# Generated by Django 5.1.1 on 2024-10-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='estatus_numero',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], db_column='estatus', default=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='parametro',
            name='estatus_parametro',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], db_column='estatus', default=True, verbose_name='Estatus'),
        ),
    ]
