# Generated by Django 5.1.1 on 2024-10-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_numero_estatus_numero_parametro_estatus_parametro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numero',
            name='estatus_numero',
        ),
        migrations.RemoveField(
            model_name='parametro',
            name='estatus_parametro',
        ),
    ]
