# Generated by Django 5.1.1 on 2024-10-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_remove_numero_estatus_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cuit_socio',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='domicilio_socio',
            field=models.CharField(blank=True, max_length=30, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='mail_socio',
            field=models.EmailField(blank=True, max_length=50, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='movil_socio',
            field=models.EmailField(blank=True, max_length=15, verbose_name='Telefono Movil'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre_socio',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono2_socio',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono_socio',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono'),
        ),
    ]
