# Generated by Django 5.1.1 on 2024-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_socio_cuit_socio_alter_socio_domicilio_socio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_alta',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_baja',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='mail_tarjeta',
            field=models.EmailField(blank=True, max_length=50, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='movil_tarjeta',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono Movil'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='telefono2_tarjeta',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='telefono_tarjeta',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='vencimiento',
            field=models.DateField(blank=True),
        ),
    ]
