# Generated by Django 5.1.1 on 2024-10-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_alter_tarjeta_fecha_alta_alter_tarjeta_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='limite_maximo_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite de Compra*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Disponible*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='vencimiento',
            field=models.DateField(verbose_name='Vencimiento*'),
        ),
    ]
