# Generated by Django 5.1.1 on 2024-10-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_alter_tarjeta_fecha_alta_alter_tarjeta_fecha_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='domicilio_socio',
            field=models.CharField(blank=True, max_length=30, verbose_name='Domicilio*'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre_socio',
            field=models.CharField(max_length=40, verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='adicional',
            field=models.IntegerField(verbose_name='Adicional*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='digito_verificador',
            field=models.IntegerField(verbose_name='Digito Verificador*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='nombre_titular',
            field=models.CharField(blank=True, max_length=40, verbose_name='Titular*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='vencimiento',
            field=models.DateTimeField(verbose_name='Vencimiento*'),
        ),
    ]
