# Generated by Django 5.1.1 on 2024-10-31 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_alter_socio_domicilio_socio_alter_socio_nombre_socio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='regitrolimite',
            name='fecha_limite',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_alta',
            field=models.DateField(default=datetime.date(2024, 10, 31), verbose_name='Fecha Alta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='vencimiento',
            field=models.DateField(verbose_name='Vencimiento*'),
        ),
    ]
