# Generated by Django 5.1.1 on 2024-10-31 21:13

import apps.maestros.models.tarjeta_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_tarjeta_numero_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_alta',
            field=models.DateField(),   #default=apps.maestros.models.tarjeta_models.current_date
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.BigIntegerField(editable=False),
        ),
    ]
