# Generated by Django 5.1.1 on 2024-11-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_alter_tarjeta_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_alta',
            field=models.DateField(verbose_name='Fecha Alta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.BigIntegerField(default=0),
        ),
    ]
