# Generated by Django 5.1.1 on 2024-11-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_alter_tarjeta_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionsocio',
            name='numero_tarjeta',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha_compra',
            field=models.DateField(blank=True, db_column='fecha', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='vencimiento_cuota',
            field=models.DateField(db_column='vencimiento', verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='cierre_actual',
            field=models.DateField(blank=True, verbose_name='Cierre Actual'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='cierre_anterior',
            field=models.DateField(blank=True, verbose_name='Cierre Anterior'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='cierre_proximo',
            field=models.DateField(blank=True, verbose_name='Proximo Cierre'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='vencimiento',
            field=models.DateField(blank=True, verbose_name='Vencimiento'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='vencimiento_anterior',
            field=models.DateField(blank=True, verbose_name='Vencimiento Anterior'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='vencimiento_proximo',
            field=models.DateField(blank=True, verbose_name='Proximo Vencimiento'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='acreditado',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha_operacion',
            field=models.DateField(db_column='fecha', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='cierre_actual',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='cierre_proximo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='cierre_ultimo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='vencimiento_actual',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='vencimiento_proximo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='vencimiento_ultimo',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vencimiento_plan',
            field=models.DateField(db_column='vencimiento'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.BigIntegerField(),
        ),
    ]
