# Generated by Django 5.1.1 on 2024-11-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_liquidacionsocio_numero_tarjeta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='id_socio',
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='id_socio',
        ),
        migrations.AddField(
            model_name='comercio',
            name='codigo_socio',
            field=models.IntegerField(default=0, verbose_name='Codigo Socio'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='codigo_socio',
            field=models.IntegerField(default=0, verbose_name='Codigo Socio*'),
        ),
        migrations.DeleteModel(
            name='Socio',
        ),
    ]
