# Generated by Django 5.1.1 on 2024-11-14 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_remove_tarjeta_id_socio_remove_comercio_id_socio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='interes_actividad',
            field=models.DecimalField(db_column='interes', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interes(%)'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='porcentaje_consumo',
            field=models.DecimalField(db_column='consumo', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Cosumo(%)'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='porcentaje_retencion_ib',
            field=models.DecimalField(db_column='retencion_ib', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Rentecion IIBB(%)'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='importe_compra',
            field=models.DecimalField(db_column='importe', decimal_places=2, max_digits=14, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='capital_cuota',
            field=models.DecimalField(db_column='capital', decimal_places=2, max_digits=14, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='importe_cuota',
            field=models.DecimalField(db_column='importe', decimal_places=2, max_digits=14, verbose_name='Importe Cuota'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='interes_cuota',
            field=models.DecimalField(db_column='interes', decimal_places=2, max_digits=14, verbose_name='Interes'),
        ),
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='importe_comision',
            field=models.DecimalField(db_column='comision', decimal_places=2, max_digits=14, verbose_name='Comision'),
        ),
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='importe_liquidacion',
            field=models.DecimalField(db_column='importe', decimal_places=2, max_digits=14, verbose_name='Importe Liquidacion'),
        ),
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='retencio_ib',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Retencion IIBB'),
        ),
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='retencion_debito_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Retencion DB/CD'),
        ),
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='retencion_ganancias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Retencion Ganancias'),
        ),
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='retencion_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Retencion IVA'),
        ),
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='total_liquidacion',
            field=models.DecimalField(blank=True, db_column='total', decimal_places=2, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='importe_gasto',
            field=models.DecimalField(blank=True, db_column='gastos', decimal_places=2, max_digits=14, verbose_name='Gastos'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='importe_interes',
            field=models.DecimalField(blank=True, db_column='interes', decimal_places=2, max_digits=14, verbose_name='Interes'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='importe_liquidacion',
            field=models.DecimalField(blank=True, db_column='importe', decimal_places=2, max_digits=14, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='importe_punitorio',
            field=models.DecimalField(blank=True, db_column='punitorio', decimal_places=2, max_digits=14, verbose_name='Punitorios'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='importe_seguro',
            field=models.DecimalField(blank=True, db_column='seguro', decimal_places=2, max_digits=14, verbose_name='Seguro'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='importe_sellado',
            field=models.DecimalField(blank=True, db_column='sellado', decimal_places=2, max_digits=14, verbose_name='Sellado'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='importe_total',
            field=models.DecimalField(blank=True, db_column='total', decimal_places=2, max_digits=14, verbose_name='Importe Total'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='limite_tarjeta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Limite Tarjeta'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='pago_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Pago Anterior'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='pago_minimo',
            field=models.DecimalField(blank=True, db_column='minimo', decimal_places=2, max_digits=14, verbose_name='Pago Minimo'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='saldo_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Saldo Anterior'),
        ),
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='su_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, verbose_name='Su Pago'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='importe_compra',
            field=models.DecimalField(db_column='importe', decimal_places=2, max_digits=14, verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='dias_mora',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='gastos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='gastos_mail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='minimo',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Pago Minimo(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='punitorios',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interes Punitorio(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_debito_credito',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Retencion DB/CD(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ganancia',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Retencion Ganancias(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ganancia_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999.99)], verbose_name='Minimo Retencion Ganancias'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ganancia_minimo_nc',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999.99)], verbose_name='Minimo Retencion Ganancias NC'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ganancia_nc',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Retencion Ganancias NC(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ib',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Retencion IIBB(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ib_general',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Renecion IIBB General(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ib_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999.99)], verbose_name='Minimo Retencion IIBB'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_iva_estacion_servicio',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Retencion IVA Est.Servicios(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_iva_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999.99)], verbose_name='Minimo Retencion IVA'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_iva_nc',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Retencion IVA NC(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='seguro',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Seguro Vida(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='sello',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Sellado(%)'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Tasa Mora(%)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='costo_financiero_plan',
            field=models.DecimalField(db_column='costo_financiero', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Costo Financiero(%)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interes_plan',
            field=models.DecimalField(db_column='interes', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interes(%)'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='limite_maximo_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de Compra*'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Disponible*'),
        ),
    ]
