# Generated by Django 5.1.1 on 2024-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_alter_actividad_interes_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liqudacioncomercio',
            name='fecha_liquidacion',
            field=models.DateField(db_column='fecha', verbose_name='Fecha'),
        ),
    ]
