# Generated by Django 5.1.1 on 2024-11-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0014_alter_liqudacioncomercio_fecha_liquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionsocio',
            name='fecha_pago',
            field=models.DateField(blank=True, verbose_name='Fecha Pago'),
        ),
    ]
