# Generated by Django 5.1.1 on 2024-11-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0015_alter_liquidacionsocio_fecha_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comercio',
            old_name='id_iva_comercio',
            new_name='id_iva',
        ),
        migrations.RenameField(
            model_name='comercio',
            old_name='id_localidad_comercio',
            new_name='id_localidad',
        ),
        migrations.RenameField(
            model_name='comercio',
            old_name='id_provincia_comercio',
            new_name='id_provincia',
        ),
        migrations.RenameField(
            model_name='comercio',
            old_name='id_sucursal_comercio',
            new_name='id_sucursal',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='id_localidad_tarjeta',
            new_name='id_localidad',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='id_provincia_tarjeta',
            new_name='id_provincia',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='id_sucursal_tarjeta',
            new_name='id_sucursal',
        ),
    ]
