# Generated by Django 5.1.1 on 2024-11-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0016_rename_id_iva_comercio_comercio_id_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='id_iva',
        ),
        migrations.AddField(
            model_name='comercio',
            name='id_tipo_iva',
            field=models.ForeignKey(db_column='id_tipo_iva', default=1, on_delete=django.db.models.deletion.PROTECT, to='maestros.tipoiva', verbose_name='IVA*'),
        ),
    ]
