# Generated by Django 5.1.1 on 2024-11-20 01:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0017_remove_comercio_id_iva_comercio_id_tipo_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametro',
            name='id_empresa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='maestros.empresa'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='retencion_ganancia_minimo_nc',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999.99)], verbose_name='Minimo Ret.Ganancias NC'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo_provincia',
            field=models.CharField(db_column='codigo', max_length=1, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoidentidad',
            name='tipo_documento_identidad',
            field=models.CharField(db_column='tipo', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoiva',
            name='codigo_iva',
            field=models.CharField(db_column='codigo', max_length=4, unique=True, verbose_name='Codigo'),
        ),
    ]
