# Generated by Django 5.1.1 on 2024-11-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0019_actividad_id_user_comercio_id_user_compra_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='codigo_comercio',
            field=models.IntegerField(db_column='codigo', unique=True, verbose_name='Codigo*'),
        ),
    ]
