# Generated by Django 5.1.1 on 2024-11-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0020_alter_comercio_codigo_comercio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='digito_verificador',
            field=models.IntegerField(blank=True, null=True, verbose_name='Digito Verificador'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='saldo_disponible',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Disponible'),
        ),
    ]
