# Generated by Django 5.1.1 on 2024-12-29 00:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0021_alter_tarjeta_digito_verificador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiqudacionComercio',
            new_name='LiquidacionComercio',
        ),
    ]
