# Generated by Django 5.1.1 on 2024-11-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0019_actividad_id_user_comercio_id_user_compra_id_user_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='user',
            name='id_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal'),
        ),
    ]
