# Generated by Django 5.1.1 on 2024-11-25 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0020_alter_comercio_codigo_comercio'),
        ('usuarios', '0002_remove_user_vendedor_user_id_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='maestros.sucursal', verbose_name='Sucursal'),
            preserve_default=False,
        ),
    ]
